<?php

namespace Database\Seeders;

use App\Models\Doctor;
use App\Models\Specialization;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DoctorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
          $doctors = [
            [
                'doctor_number' => 'D001',
                'name' => 'Ahmad Yusuf',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.PD',
                'phone' => '081234567890',
                'address' => 'Jl. Merdeka No.1, Jakarta',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Penyakit Dalam',
                'description' => 'Dokter spesialis penyakit dalam dengan pengalaman lebih dari 15 tahun. Fokus pada penanganan diabetes, hipertensi, dan penyakit metabolik.',
            ],
            [
                'doctor_number' => 'D002',
                'name' => 'Rina Kartika',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.A',
                'phone' => '081298765432',
                'address' => 'Jl. Kenangan No.12, Bandung',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Anak',
                'description' => 'Spesialis anak yang berdedikasi dengan pendekatan ramah anak. Melayani konsultasi tumbuh kembang, imunisasi, dan penanganan penyakit anak umum.',
            ],
            [
                'doctor_number' => 'D003',
                'name' => 'Budi Santoso',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.B',
                'phone' => '082112345678',
                'address' => 'Jl. Sehat No.45, Surabaya',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Bedah',
                'description' => 'Ahli bedah berpengalaman di berbagai prosedur umum dan khusus. Mengedepankan keselamatan pasien dan pemulihan optimal.',
            ],
            [
                'doctor_number' => 'D004',
                'name' => 'Citra Dewi',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.OG',
                'phone' => '087811223344',
                'address' => 'Jl. Kebahagiaan No.7, Yogyakarta',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Kandungan',
                'description' => 'Spesialis kandungan dan kebidanan yang peduli. Memberikan layanan kesehatan reproduksi wanita, kehamilan, persalinan, dan pasca-persalinan.',
            ],
            [
                'doctor_number' => 'D005',
                'name' => 'Eko Prasetyo',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.S',
                'phone' => '085699887766',
                'address' => 'Jl. Otak Kanan No.23, Semarang',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Saraf',
                'description' => 'Dokter saraf dengan keahlian dalam diagnosis dan penanganan gangguan sistem saraf, seperti stroke, epilepsi, dan sakit kepala kronis.',
            ],
            [
                'doctor_number' => 'D006',
                'name' => 'Fani Wijaya',
                'front_title' => 'Drg.',
                'back_title' => '',
                'phone' => '081344556677',
                'address' => 'Jl. Senyum Indah No.10, Medan',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Gigi',
                'description' => 'Dokter gigi umum yang menyediakan layanan perawatan gigi rutin, penambalan, pencabutan, dan pembersihan karang gigi untuk segala usia.',
            ],
            [
                'doctor_number' => 'D007',
                'name' => 'Gita Permata',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.M',
                'phone' => '081122334455',
                'address' => 'Jl. Pandangan Jauh No.8, Makassar',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Mata',
                'description' => 'Spesialis mata yang kompeten dalam menangani berbagai masalah penglihatan, katarak, glaukoma, dan kelainan refraksi.',
            ],
            [
                'doctor_number' => 'D008',
                'name' => 'Hadi Susanto',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.THT-KL',
                'phone' => '089977665544',
                'address' => 'Jl. Pendengaran No.3, Palembang',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'THT',
                'description' => 'Ahli Telinga, Hidung, Tenggorokan, Kepala & Leher. Menangani infeksi, alergi, gangguan pendengaran, dan masalah sinus.',
            ],
            [
                'doctor_number' => 'D009',
                'name' => 'Indah Lestari',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.KK',
                'phone' => '081700998877',
                'address' => 'Jl. Kulit Bersih No.15, Malang',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Kulit dan Kelamin',
                'description' => 'Dokter spesialis kulit dan kelamin yang fokus pada kesehatan kulit, rambut, kuku, serta penanganan penyakit menular seksual.',
            ],
            [
                'doctor_number' => 'D010',
                'name' => 'Joko Widodo',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.JP',
                'phone' => '081211223344',
                'address' => 'Jl. Jantung Sehat No.5, Surabaya',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Penyakit Dalam',
                'description' => 'Spesialis jantung terkemuka dengan keahlian dalam diagnosis dan penanganan penyakit jantung koroner, aritmia, dan gagal jantung.',
            ],
            [
                'doctor_number' => 'D011',
                'name' => 'Kurnia Fitri',
                'front_title' => 'Dr.',
                'back_title' => '',
                'phone' => '081355443322',
                'address' => 'Jl. Kesehatan Umum No.20, Pontianak',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Umum',
                'description' => 'Dokter umum yang memberikan pelayanan kesehatan komprehensif, mulai dari pemeriksaan rutin hingga penanganan penyakit ringan.',
            ],
            // --- Data dokter tambahan ---
            [
                'doctor_number' => 'D012',
                'name' => 'Daniel Pratama',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.PD',
                'phone' => '081223344556',
                'address' => 'Jl. Kusuma Bangsa No.50, Jakarta',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Penyakit Dalam',
                'description' => 'Dokter penyakit dalam dengan fokus pada gastroenterologi dan hepatologi. Berkomitmen pada diagnosa akurat dan terapi yang efektif.',
            ],
            [
                'doctor_number' => 'D013',
                'name' => 'Sarah Wijayanti',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.A',
                'phone' => '081276543210',
                'address' => 'Jl. Ceria Anak No.8, Bandung',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Anak',
                'description' => 'Dokter anak dengan keahlian di bidang alergi dan imunologi pediatrik. Memberikan edukasi dan penanganan untuk orang tua dan anak-anak.',
            ],
            [
                'doctor_number' => 'D014',
                'name' => 'Kevin Tanuwijaya',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.B',
                'phone' => '082198765432',
                'address' => 'Jl. Bedah Jaya No.22, Surabaya',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Bedah',
                'description' => 'Spesialis bedah ortopedi yang ahli dalam penanganan cedera tulang dan sendi. Menggunakan teknik bedah minimal invasif untuk pemulihan cepat.',
            ],
            [
                'doctor_number' => 'D015',
                'name' => 'Lia Amelia',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.OG',
                'phone' => '087855443322',
                'address' => 'Jl. Ibu Pertiwi No.18, Yogyakarta',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Kandungan',
                'description' => 'Dokter obgyn dengan fokus pada kesehatan reproduksi remaja dan menopause. Memberikan konsultasi yang komprehensif dan suportif.',
            ],
            [
                'doctor_number' => 'D016',
                'name' => 'Wisnu Murti',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.S',
                'phone' => '085611223344',
                'address' => 'Jl. Saraf Pusat No.11, Semarang',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Saraf',
                'description' => 'Neurolog ahli dalam penanganan migrain, vertigo, dan gangguan tidur. Berusaha memberikan kualitas hidup yang lebih baik bagi pasien.',
            ],
            [
                'doctor_number' => 'D017',
                'name' => 'Dewi Maharani',
                'front_title' => 'Drg.',
                'back_title' => 'Sp.Ort',
                'phone' => '081377889900',
                'address' => 'Jl. Gigi Sehat No.7, Medan',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Gigi', // Atau spesialisasi ortodonti jika ada
                'description' => 'Dokter gigi spesialis ortodonti yang berfokus pada perbaikan susunan gigi dan rahang untuk senyum yang indah dan fungsional.',
            ],
            [
                'doctor_number' => 'D018',
                'name' => 'Rio Adriansyah',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.M',
                'phone' => '081166554433',
                'address' => 'Jl. Mata Terang No.9, Makassar',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Mata',
                'description' => 'Oftalmolog dengan fokus pada penanganan retinopati diabetik dan degenerasi makula. Menggunakan teknologi terkini untuk diagnosa dan terapi.',
            ],
            [
                'doctor_number' => 'D019',
                'name' => 'Amelia Putri',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.THT-KL',
                'phone' => '089911223344',
                'address' => 'Jl. THT Utama No.14, Palembang',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'THT',
                'description' => 'Spesialis THT-KL yang ahli dalam penanganan gangguan pendengaran pada anak dan dewasa, serta operasi amandel dan adenoid.',
            ],
            [
                'doctor_number' => 'D020',
                'name' => 'Rama Wijaya',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.KK',
                'phone' => '081722334455',
                'address' => 'Jl. Dermatologi No.25, Malang',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Kulit dan Kelamin',
                'description' => 'Dermatolog dengan minat khusus pada dermatologi kosmetik dan penanganan jerawat kronis. Memberikan solusi perawatan kulit yang personal.',
            ],
             [
                'doctor_number' => 'D021',
                'name' => 'Siti Aisyah',
                'front_title' => 'Dr.',
                'back_title' => '',
                'phone' => '081234560001',
                'address' => 'Jl. Jendral Sudirman No.10, Jakarta',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Umum',
                'description' => 'Dokter umum yang ramah dan kompeten, siap melayani konsultasi kesehatan primer dan memberikan rujukan bila diperlukan.',
            ],
            [
                'doctor_number' => 'D022',
                'name' => 'Bayu Wicaksono',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.PD',
                'phone' => '081234560002',
                'address' => 'Jl. Pahlawan No.22, Surabaya',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Penyakit Dalam',
                'description' => 'Internis dengan fokus pada penyakit infeksi dan imunologi. Berpengalaman dalam penanganan kasus kompleks.',
            ],
            [
                'doctor_number' => 'D023',
                'name' => 'Clara Angelina',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.A',
                'phone' => '081234560003',
                'address' => 'Jl. Kartini No.15, Semarang',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Anak',
                'description' => 'Dokter spesialis anak yang berfokus pada nutrisi dan gizi anak, serta penanganan masalah pencernaan pada bayi dan balita.',
            ],
            [
                'doctor_number' => 'D024',
                'name' => 'Dedi Iskandar',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.B',
                'phone' => '081234560004',
                'address' => 'Jl. Diponegoro No.8, Bandung',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Bedah',
                'description' => 'Ahli bedah umum yang berpengalaman dalam bedah digestif dan laparoskopi. Mengutamakan pemulihan cepat dan minim rasa sakit.',
            ],
            [
                'doctor_number' => 'D025',
                'name' => 'Erlina Kusuma',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.OG',
                'phone' => '081234560005',
                'address' => 'Jl. Gatot Subroto No.30, Yogyakarta',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Kandungan',
                'description' => 'Spesialis kandungan yang berfokus pada program kehamilan dan infertilitas. Memberikan dukungan penuh bagi pasangan yang ingin memiliki buah hati.',
            ],
            [
                'doctor_number' => 'D026',
                'name' => 'Ferry Gunawan',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.S',
                'phone' => '081234560006',
                'address' => 'Jl. Thamrin No.25, Medan',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Saraf',
                'description' => 'Dokter saraf dengan keahlian dalam penanganan nyeri kronis dan neuropati. Menggunakan pendekatan multimodal untuk penanganan nyeri.',
            ],
            [
                'doctor_number' => 'D027',
                'name' => 'Grace Natalia',
                'front_title' => 'Drg.',
                'back_title' => 'Sp.KG',
                'phone' => '081234560007',
                'address' => 'Jl. Imam Bonjol No.40, Makassar',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Gigi', // Atau spesialisasi Konservasi Gigi jika ada
                'description' => 'Spesialis konservasi gigi yang fokus pada perawatan endodontik (perawatan saluran akar) dan restorasi gigi yang rusak.',
            ],
            [
                'doctor_number' => 'D028',
                'name' => 'Hendra Setiawan',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.M',
                'phone' => '081234560008',
                'address' => 'Jl. Sudirman No.55, Palembang',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Mata',
                'description' => 'Dokter mata yang ahli dalam bedah refraktif (LASIK) dan penanganan kelainan kornea. Membantu pasien mencapai penglihatan optimal.',
            ],
            [
                'doctor_number' => 'D029',
                'name' => 'Irma Suryani',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.THT-KL',
                'phone' => '081234560009',
                'address' => 'Jl. Proklamasi No.1, Malang',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'THT',
                'description' => 'Ahli THT-KL yang berfokus pada penanganan gangguan suara dan menelan. Memberikan terapi komprehensif untuk masalah komunikasi.',
            ],
            [
                'doctor_number' => 'D030',
                'name' => 'Kevin Pratama',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.KK',
                'phone' => '081234560010',
                'address' => 'Jl. Majapahit No.100, Pontianak',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Kulit dan Kelamin',
                'description' => 'Dokter kulit dan kelamin yang ahli dalam penanganan eksim, psoriasis, dan infeksi kulit. Memberikan perawatan yang sesuai dengan kondisi kulit pasien.',
            ],
            [
                'doctor_number' => 'D031',
                'name' => 'Linda Susanti',
                'front_title' => 'Dr.',
                'back_title' => '',
                'phone' => '081234560011',
                'address' => 'Jl. Merdeka No.3, Balikpapan',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Umum',
                'description' => 'Dokter umum yang berdedikasi untuk edukasi kesehatan masyarakat dan pencegahan penyakit. Siap menjadi mitra kesehatan keluarga Anda.',
            ],
            [
                'doctor_number' => 'D032',
                'name' => 'Michael Chandra',
                'front_title' => 'Dr.',
                'back_title' => 'Sp.JP',
                'phone' => '081234560012',
                'address' => 'Jl. Asia Afrika No.5, Jakarta',
                'photo' => 'doctors/doctor.png',
                'specialization_id' => 'Penyakit Dalam', // Karena Sp.JP adalah bagian dari Penyakit Dalam terkait kardiovaskular
                'description' => 'Kardiolog intervensi yang fokus pada penanganan penyakit jantung koroner melalui prosedur kateterisasi. Berpengalaman dalam pemasangan *stent*.',
            ],
        ];


        foreach ($doctors as $doctor) {
            $spesialis = Specialization::where('name', $doctor['specialization_id'])->first();
            $doctor['specialization_id'] = $spesialis ? $spesialis->id : null;
            Doctor::create($doctor);
        }

    }
}
